# Generated by Django 3.2.8 on 2021-11-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=35)),
                ('kilometros', models.IntegerField()),
                ('categoria', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
