# Generated by Django 3.2.8 on 2021-11-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletCar', '0002_auto_20211110_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='coche',
            name='anyo',
            field=models.IntegerField(max_length=5),
        ),
        migrations.AddField(
            model_name='coche',
            name='categorias',
            field=models.ManyToManyField(to='appOutletCar.Categoria'),
        ),
    ]
