# Generated by Django 3.2.8 on 2021-11-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletCar', '0003_auto_20211110_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='anyo',
            field=models.IntegerField(),
        ),
    ]
