# Generated by Django 3.2.8 on 2021-11-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletCar', '0004_alter_coche_anyo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
