# Generated by Django 3.2.8 on 2021-11-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletCar', '0005_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='coche',
            name='foto',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
