# Generated by Django 3.2.8 on 2021-11-10 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletCar', '0006_coche_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coche',
            name='categorias',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Coche',
        ),
    ]
