# Generated by Django 3.2.8 on 2021-11-10 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appOutletCar', '0007_auto_20211110_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaCoche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOutletCar.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=35)),
                ('kilometros', models.IntegerField()),
                ('anyo', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
                ('foto', models.ImageField(null=True, upload_to='fotos')),
                ('categorias', models.ManyToManyField(through='appOutletCar.CategoriaCoche', to='appOutletCar.Categoria')),
            ],
        ),
        migrations.AddField(
            model_name='categoriacoche',
            name='coche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOutletCar.coche'),
        ),
    ]
