# Generated by Django 3.2.8 on 2021-11-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletCar', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
