# Generated by Django 3.2.8 on 2021-11-10 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletCar', '0009_alter_coche_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMarca', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='coche',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appOutletCar.marca'),
        ),
    ]
