# Generated by Django 3.2.8 on 2021-11-10 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletCar', '0010_auto_20211110_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre',
            new_name='nombreCategoria',
        ),
    ]
