# Generated by Django 3.2.8 on 2021-11-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletCar', '0011_rename_nombre_categoria_nombrecategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='foto',
            field=models.ImageField(null=True, upload_to='static/fotos'),
        ),
    ]
