# Generated by Django 3.2.8 on 2021-11-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletCar', '0012_alter_coche_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
