# Generated by Django 3.2.8 on 2021-11-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletCar', '0014_alter_coche_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='logo',
            field=models.ImageField(null=True, upload_to='static/fotos/logosMarcas'),
        ),
        migrations.AlterField(
            model_name='coche',
            name='foto',
            field=models.ImageField(null=True, upload_to='static/fotos/fotosCoches'),
        ),
    ]
