# Generated by Django 3.2.8 on 2021-11-16 12:18

import appOutletCar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletCar', '0016_auto_20211116_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coche',
            name='slug',
            field=models.SlugField(default=appOutletCar.models.Coche.nombreSlug, unique=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='slug',
            field=models.SlugField(default=appOutletCar.models.Marca.nombreSlug, unique=True),
        ),
    ]
