# Generated by Django 3.2.8 on 2021-11-16 12:18

import appOutletCar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletCar', '0017_auto_20211116_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(default=appOutletCar.models.Categoria.nombreSlug, unique=True),
        ),
    ]
