# Generated by Django 3.2.8 on 2021-11-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOutletCar', '0018_alter_categoria_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=20), unique=True),
        ),
        migrations.AlterField(
            model_name='coche',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=35), unique=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=20), unique=True),
        ),
    ]
